global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "kong"
    static_configs:
      - targets: ["kong:8001"]
    metrics_path: /metrics

  - job_name: "publishers"
    static_configs:
      - targets: ["publishers:8000"]
    metrics_path: /metrics

  - job_name: "tasks"
    static_configs:
      - targets: ["tasks:8000"]
    metrics_path: /metrics

  - job_name: "qa"
    static_configs:
      - targets: ["qa:8000"]
    metrics_path: /metrics

  - job_name: "users"
    static_configs:
      - targets: ["users:8000"]
    metrics_path: /metrics
